site_name: Kayak Documentation
site_url: https://emozley.com/kayak/
repo_name: emozley/kayak
repo_url: https://github.com/emozley/kayak

copyright: Copyright &copy; 2021 E. L. Mozley

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emozley
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/imautonor

theme:
  name: material
  icon:
    logo: material/school
  palette:
    primary: blue
    accent: blue

nav:
  - Home: index.md
  - Why Kayak: why-kayak.md
  - Guide:
      - Installation: guide/installation.md
      - Package Basics: guide/packages.md
  - Get help with Kayak: help.md
  - Advanced:
      - Proxies: advanced/proxies.md
      - Package links: advanced/package-links.md

plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - meta
