site_name: Kayak Documentation
site_url: https://emozley.uk/kayak/
repo_name: ElliottLMz/kayak
repo_url: https://github.com/ElliottLMz/kayak

copyright: Copyright &copy; 2020 Elliott Mozley

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/elliottlmz
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/elliott_lmz

theme:
  name: material
  icon:
    logo: material/get_app
  palette:
    primary: blue
    accent: blue

nav:
  - Home: index.md

plugins:
  - search
  - git-revision-date-localized
  - minify

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - meta
